language: r
sudo: required
dist: bionic
cache:
  - directories:
    - $HOME/R/Library


addons:
  apt:
    packages:
      - libxml2-dev
      - tk-dev
      - libgit2-dev
      - libmagick++-dev

r:
#  - bioc-devel
  - bioc-release
  - 3.6.0

stages:
  - Setup Cache
  - Test

# setup cache first
jobs:
  include:
#    - stage: Setup Cache
#      r: bioc-devel
#      script: true
    - stage: Setup Cache
      r: bioc-release
      script: true
    - stage: Setup Cache
      r: 3.6.0
      script: true

before_install:
  - tlmgr install index marginfix bera nowidow parnotes

install:
  - R --version
  - Rscript setupEnv.R
  - R -e "install.packages('magick')"

script:
  - R CMD build --no-build-vignettes .
  - R CMD BiocCheck --no-check-vignettes *tar.gz
  - R CMD check --no-vignettes --timings *tar.gz
  - cd vignettes && R CMD Sweave --engine=knitr::knitr --pdf FraseR.Rnw
  - R -e 'devtools::run_examples()'
  - R -e 'devtools::test()'

after_success:
  - test $TRAVIS_BUILD_STAGE_NAME = "Test" && 
      travis_wait 30 Rscript -e 'covr::codecov()'
